# Copyright (C) 2026 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "tst_ownership"
version.workspace = true
edition.workspace = true
description = "Tests for objects ownership."

[dependencies]
qtbridge = { path = "../../crates/qtbridge" }

[[test]]
name = "rust_owned_tests"
path = "tests/rust_owned_tests.rs"
harness = false

[[test]]
name = "shared_ownership_tests"
path = "tests/shared_ownership_tests.rs"
harness = false

[[test]]
name = "inflight_handover_tests"
path = "tests/inflight_handover_tests.rs"
harness = false

[[test]]
name = "no_engine_tests"
path = "tests/no_engine_tests.rs"
harness = false

[[test]]
name = "automatic_collection_tests"
path = "tests/automatic_collection_tests.rs"
harness = false

[[test]]
name = "unattached_tests"
path = "tests/unattached_tests.rs"
harness = false

[[test]]
name = "cpp_ownership_tests"
path = "tests/cpp_ownership_tests.rs"
harness = false
