# Copyright (C) 2026 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "tst_qobject_macro"
version.workspace = true
edition.workspace = true
description = "Tests for objects annotated with the `#[qobject]` macro."

[dependencies]
qtbridge = { path = "../../crates/qtbridge" }
qtbridge-type-lib = { path = "../../crates/qtbridge-type-lib" }
quicktest = { path = "../../quicktest" }

[[test]]
name = "property_nested_types_tests"
path = "tests/property_nested_types_tests.rs"
harness = false

[[test]]
name = "property_nested_types_impl_tests"
path = "tests/property_nested_types_impl_tests.rs"
harness = false

[[test]]
name = "property_item_model_tests"
path = "tests/property_item_model_tests.rs"
harness = false

[[test]]
name = "slot_nested_types_tests"
path = "tests/slot_nested_types_tests.rs"
harness = false

[[test]]
name = "slot_tests"
path = "tests/slot_tests.rs"
harness = false

[[test]]
name = "slot_return_tests"
path = "tests/slot_return_tests.rs"
harness = false

[[test]]
name = "slot_return_vec_tests"
path = "tests/slot_return_vec_tests.rs"
harness = false

[[test]]
name = "slot_vec_tests"
path = "tests/slot_vec_tests.rs"
harness = false

[[test]]
name = "signal_vec_tests"
path = "tests/signal_vec_tests.rs"
harness = false

[[test]]
name = "signal_nested_types_tests"
path = "tests/signal_nested_types_tests.rs"
harness = false

[[test]]
name = "qml_method_invoker_tests"
path = "tests/qml_method_invoker_tests.rs"
harness = false

[[test]]
name = "property_nested_lists"
path = "tests/property_nested_lists.rs"
harness = false

[[test]]
name = "signal_slot_nested_lists_tests"
path = "tests/signal_slot_nested_lists_tests.rs"
harness = false

[[test]]
name = "property_nested_lists_getter_setter_tests"
path = "tests/property_nested_lists_getter_setter_tests.rs"
harness = false

[[test]]
name = "property_default_property_tests"
path = "tests/property_default_property_tests.rs"
harness = false

[[test]]
name = "qml_overload_tests"
path = "tests/qml_overload_tests.rs"
harness = false
