# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[workspace.package]
edition = "2024"
rust-version = "1.88.0"
version = "0.2.0"
repository = "https://code.qt.io/cgit/qt/qtbridge-rust.git/"
license = "LicenseRef-Qt-Commercial OR LGPL-3.0-only"

[workspace.dependencies]
cxx = { version = "1.0.158", features = ["c++17", "std"] }
cxx-build = { version = "1.0.158", features = [ "parallel" ] }
# TODO: switch to cxx-qt from crates.io
cxx-qt = { git = "https://github.com/KDAB/cxx-qt", rev = "a733e34952481a9f40e9dc5ab22e4ac37339d0a7" }
cxx-qt-lib = { git = "https://github.com/KDAB/cxx-qt", rev = "a733e34952481a9f40e9dc5ab22e4ac37339d0a7", features = ["qt_gui", "qt_qml"] }
linkme = "0.3"
serde_json = "1"
proc-macro2 = "1.0.95"
quote = "1.0.40"
syn = { version = "2.0.103", features = ["extra-traits", "full"] }
qt-build-utils = ">=0.9"
qt-version = { version = "0.1.4", features = ["qt_version_at_least_6_10"] }
qtbridge-build-utils = { path = "crates/qtbridge-build-utils", version = "0.2.0" }
qtbridge-gen-common = { path = "crates/qtbridge-gen-common", version = "0.2.0" }
qtbridge-gen = { path = "crates/qtbridge-gen", version = "0.2.0" }
qtbridge-type-lib = { path = "crates/qtbridge-type-lib", version = "0.2.0" }
qtbridge-interfaces = { path = "crates/qtbridge-interfaces", version = "0.2.0" }
qtbridge-runtime = { path = "crates/qtbridge-runtime", version = "0.2.0" }
qtbridge = { path = "crates/qtbridge", version = "0.2.0" }

[workspace]
resolver = "2"

members = [
    "code_gen/qt_type_gen",
    "code_gen/qt_type_gen_lib",

    "crates/qtbridge",
    "crates/qtbridge-build-utils",
    "crates/qtbridge-gen-common",
    "crates/qtbridge-gen",
    "crates/qtbridge-type-lib",
    "crates/qtbridge-interfaces",
    "crates/qtbridge-runtime",
    "crates/qt-artifacts",
    "crates/qt-version",

    "quicktest",
    "quicktest/quicktest_gen",

    "apps/color_palette",
    "apps/hello_world",
    "apps/minimal_app",
    "apps/host_monitor",

    "test/tst_qobject_macro",
    "test/tst_qt_ifaces",
    "test/tst_metatype",
    "test/tst_ownership",
    "test/tst_serde_json",
    "test/tst_linkme",
    "test/tst_qtbridge_gen_common",
    "test/quick/tst_qobject",
    "test/quick/tst_qabstractitemmodel",
    "test/quick/tst_generic_itemmodel",
    "test/quick/tst_qresource",
    "test/quick/tst_qlistmodel",
    "test/quick/tst_qtablemodel",
    "test/quick/tst_qml_element",
]

# only core code and lightweight tests
default-members = [
    "crates/qtbridge",
    "crates/qtbridge-build-utils",
    "crates/qtbridge-gen-common",
    "crates/qtbridge-gen",
    "crates/qtbridge-type-lib",
    "crates/qtbridge-interfaces",
    "crates/qtbridge-runtime",
    "crates/qt-artifacts",
    "crates/qt-version",

    "test/tst_qobject_macro",
    "test/tst_qt_ifaces",
    "test/tst_metatype",
]

[profile.release.build-override]
# In release mode build script may be running twice (unlike debug)
# because a package being dependency is built twice with different optimization settings.
# Hardcode optimization level to help cargo deduplicate dependencies and run build script only once.
opt-level = 3
