// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
// This file was auto generated by qt_type_gen package
// from the input file://./../../../../../../code_gen/qt_type_gen/src/input/testlib/qsignalspy.rs

use crate::{QObject, QVariantList};
use cxx::UniquePtr;
use std::pin::Pin;
#[cxx::bridge]
mod ffi {
    unsafe extern "C++" {
        include!("qtbridge-type-lib/src/testlib/qsignalspy/cpp/qsignalspy.h");
        /// The `QSignalSpy` is a struct that enables introspection of signal emission.
        ///
        /// A `QSignalSpy` can connect to a signal of a `QObject` and record each time the signal is emitted.
        /// `QSignalSpy` itself is a `QVariantList`. Each emission of the signal will append one item to the list, containing the arguments of the signal.
        ///
        /// See also: [QSignalSpy documentation](https://doc.qt.io/qt-6/qsignalspy.html#details).
        type QSignalSpy;
        include!("qtbridge-type-lib/src/core/qlist/cpp/qlist_qvariant.h");
        type QList_QVariant = crate::QList_QVariant;
        include!("qtbridge-type-lib/src/core/qobject/cpp/qobject.h");
        type QObject = crate::QObject;
    }
    #[namespace = "rust::bridge::qsignalspy"]
    unsafe extern "C++" {
        # [rust_name = inline_cpp_fn_new]
        fn inlineCppFn_new(qobject: &QObject, signal_name: &str) -> UniquePtr<QSignalSpy>;
        # [rust_name = inline_cpp_fn_count]
        fn inlineCppFn_count(_obj: &QSignalSpy) -> isize;
        # [rust_name = inline_cpp_fn_take_at]
        fn inlineCppFn_take_at(_obj: Pin<&mut QSignalSpy>, idx: isize) -> QList_QVariant;
        # [rust_name = inline_cpp_fn_take_first]
        fn inlineCppFn_take_first(_obj: Pin<&mut QSignalSpy>) -> QList_QVariant;
        # [rust_name = inline_cpp_fn_take_last]
        fn inlineCppFn_take_last(_obj: Pin<&mut QSignalSpy>) -> QList_QVariant;
    }
}
#[allow(dead_code)]
#[allow(unused_imports)]
pub use ffi::QSignalSpy;
impl QSignalSpy {
    #[allow(dead_code)]
    /// Creates a new `QSignalSpy` that listens for emissions of a signal of the `qobject`.
    ///
    /// # Arguments
    ///
    /// * `signal_name` - The name of the signal function to observe.
    pub fn new(qobject: &QObject, signal_name: &str) -> UniquePtr<Self> {
        let cpp = ffi::inline_cpp_fn_new;
        let ptr = cpp(qobject, signal_name);
        if ptr.is_null() {
            panic!("Failed to create QSignalSpy")
        }
        ptr
    }
    #[allow(dead_code)]
    /// Returns the number of items currently stored in the underlying [QList][crate::QList].
    pub fn count(&self) -> isize {
        let cpp = ffi::inline_cpp_fn_count;
        cpp(self)
    }
    #[allow(dead_code)]
    /// Removes the element at position `idx` from the underlying [QList][crate::QList] and returns it.
    pub fn take_at(mut self: Pin<&mut Self>, idx: isize) -> QVariantList {
        let cpp = ffi::inline_cpp_fn_take_at;
        cpp(self.as_mut(), idx)
    }
    #[allow(dead_code)]
    /// Removes the first item from the underlying [QList][crate::QList] and returns it.
    pub fn take_first(mut self: Pin<&mut Self>) -> QVariantList {
        let cpp = ffi::inline_cpp_fn_take_first;
        cpp(self.as_mut())
    }
    #[allow(dead_code)]
    /// Removes the last item from the underlying [QList][crate::QList] and returns it.
    pub fn take_last(mut self: Pin<&mut Self>) -> QVariantList {
        let cpp = ffi::inline_cpp_fn_take_last;
        cpp(self.as_mut())
    }
}
