pub const GENERATED_FILES_BRIDGE: &[&'static str] = &[
    "src/generated/core/qjsonarray/qjsonarray.rs",
    "src/generated/core/qjsonobject/qjsonobject.rs",
    "src/generated/core/qjsonvalue/qjsonvalue.rs",
    "src/generated/core/qlist/qlist_ptr_mut_qobject.rs",
    "src/generated/core/qlist/qlist_qvariant.rs",
    "src/generated/core/qmap/qmap_qstring_qvariant.rs",
    "src/generated/core/qmetaobject/qmetaobject.rs",
    "src/generated/core/qmetatype/qmetatype.rs",
    "src/generated/core/qmetatypeinterface/qmetatypeinterface.rs",
    "src/generated/core/qobject/qobject.rs",
    "src/generated/core/qqmllistproperty/qqmllistproperty.rs",
    "src/generated/core/qvariant/qvariant.rs",
    "src/generated/gui/qguiapplication/qguiapplication.rs",
    "src/generated/qml/qqmlapplicationengine/qqmlapplicationengine.rs",
    "src/generated/testlib/qsignalspy/qsignalspy.rs",
];
