pub const GENERATED_FILES_CPP: &[&'static str] = &[
    "src/generated/core/qjsonarray/cpp/qjsonarray.cpp",
    "src/generated/core/qjsonobject/cpp/qjsonobject.cpp",
    "src/generated/core/qjsonvalue/cpp/qjsonvalue.cpp",
    "src/generated/core/qlist/cpp/qlist_qvariant.cpp",
    "src/generated/core/qmetaobject/cpp/qmetaobject.cpp",
    "src/generated/core/qmetatype/cpp/qmetatype.cpp",
    "src/generated/core/qmetatypeinterface/cpp/qmetatypeinterface.cpp",
    "src/generated/core/qobject/cpp/qobject.cpp",
    "src/generated/core/qqmllistproperty/cpp/qqmllistproperty.cpp",
    "src/generated/core/qvariant/cpp/qvariant.cpp",
    "src/generated/gui/qguiapplication/cpp/qguiapplication.cpp",
    "src/generated/qml/qqmlapplicationengine/cpp/qqmlapplicationengine.cpp",
    "src/generated/testlib/qsignalspy/cpp/qsignalspy.cpp",
];
