// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

pub mod dispatchmetacall;
pub mod dynamicmetaobjectbuilder;
pub mod dynamicmetaobjectdata;
pub mod qmetatypeget;
pub mod qml_method_invoker;
pub mod qapp;
pub mod qmetainfo;
pub mod qml_register;
pub mod qmlprivate;
pub(crate) mod qqmllistproperty;
pub mod qresource;
pub mod qobjectholder;
pub mod qproxies;
pub mod qmetatype_compatible;
pub mod qmetatypeforqobject;
pub mod qmodelitem;
pub mod qpropertymember;
pub mod qvariant_convert;
pub mod registry;
pub mod rustobjectgetter;
pub(crate) mod serde_tools;

pub use dispatchmetacall::DispatchMetaCall;
pub use dynamicmetaobjectbuilder::{DynamicMetaObjectBuilder, create_dynamic_meta_object_builder};
pub use dynamicmetaobjectdata::DynamicMetaObjectData;
pub use qapp::QApp;
pub use qmetainfo::QMetaInfo;
pub use qmetatypeget::QMetaTypeGet;
pub use qml_register::QmlRegister;
pub use qobjectholder::QObjectHolder;
pub use qml_method_invoker::QmlMethodInvoker;
pub use qmodelitem::QModelItem;
pub use qmetatype_compatible::QMetaTypeCompatible;
pub use qpropertymember::{QPropertyMember, get_meta_type_of_fn_return_value};
pub use qvariant_convert::{QVariantConvertible, ToQVariant, TryFromQVariant};
pub use registry::{live_count as live_object_count, live_proxy_count};

#[cfg(feature = "linkme")]
pub use qmlprivate::QML_REGISTER_CALLBACKS;
#[cfg(feature = "linkme")]
pub use qmlprivate::call_qml_register_callbacks;
// Re-exported for the code generated by #[qobject] when the `linkme` feature
// is enabled, so that user crates do not need to depend on the linkme crate
// themselves.
#[cfg(feature = "linkme")]
#[doc(hidden)]
pub use linkme;
