# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "qt_type_gen"
version = "0.1.0"
edition.workspace = true
description = "Build script performing generation of basic type library using qt_type_gen_lib"

[dependencies]
qtbridge-build-utils = { path = "../../crates/qtbridge-build-utils" }
qtbridge-gen-common = { path = "../qtbridge-gen-common" }
qt_type_gen_lib = { path = "../qt_type_gen_lib" }
