// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
// This file was auto generated by qt_type_gen package
// from the input file://./../../../../../../code_gen/qt_type_gen/src/input/core/qqmllistproperty.rs

use crate::{QMetaType, QObject, QVariant};
#[cxx::bridge]
mod ffi {
    unsafe extern "C++" {
        include!("qtbridge-type-lib/src/core/qqmllistproperty/cpp/qqmllistproperty.h");
        include!("qtbridge-type-lib/src/core/qmetatype/cpp/qmetatype.h");
        type QMetaType = crate::QMetaType;
        include!("qtbridge-type-lib/src/core/qobject/cpp/qobject.h");
        type QObject = crate::QObject;
        include!("qtbridge-type-lib/src/core/qvariant/cpp/qvariant.h");
        type QVariant = crate::QVariant;
    }
    #[namespace = "rust::bridge::qqmllistproperty"]
    unsafe extern "C++" {
        # [rust_name = inline_cpp_fn_list_property_to_qvariant]
        unsafe fn inlineCppFn_list_property_to_qvariant(
            meta_type: &QMetaType,
            object: *mut QObject,
            data: *mut u8,
            append_fn: usize,
            count_fn: usize,
            at_fn: usize,
            clear_fn: usize,
        ) -> QVariant;
    }
}
#[allow(dead_code)]
/// Build a `QVariant` holding a `QQmlListProperty<QObject>` stamped with the per-type list metatype.
pub unsafe fn list_property_to_qvariant(
    meta_type: &QMetaType,
    object: *mut QObject,
    data: *mut u8,
    append_fn: usize,
    count_fn: usize,
    at_fn: usize,
    clear_fn: usize,
) -> QVariant {
    let cpp = ffi::inline_cpp_fn_list_property_to_qvariant;
    unsafe { cpp(meta_type, object, data, append_fn, count_fn, at_fn, clear_fn) }
}
