# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "qtbridge"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Meta-package for Qt Bridge"

[dependencies]
qtbridge-build-utils = { workspace = true }
qtbridge-gen = { workspace = true }
qtbridge-type-lib = { workspace = true }
qtbridge-runtime = { workspace = true }
qtbridge-interfaces = { workspace = true }

[features]
linkme = ["qtbridge-gen/linkme", "qtbridge-runtime/linkme"]
serde_json = ["qtbridge-runtime/serde_json"]
