// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
// This file was auto generated by qt_type_gen package
// from the input file://./../../../../../../../code_gen/qt_type_gen/src/input/core/qobject.rs

#include "qobject.h"

namespace rust::bridge::qobject {

void inlineCppFn_delete(QObject *obj)
{
    delete obj;
}

void inlineCppFn_destruct(QObject *obj)
{
    obj->~QObject();
}

QMetaObject const *inlineCppFn_get_qmeta_object(QObject const &self)
{
    return self.metaObject();
}

QVariant inlineCppFn_property(QObject const &self, rust::Slice<uint8_t const> name)
{
    return self.property(reinterpret_cast<const char *>(name.data()));
}

bool inlineCppFn_set_property(QObject &self, rust::Slice<uint8_t const> name, QVariant value)
{
    return self.setProperty(reinterpret_cast<const char *>(name.data()), value);
}

} // namespace rust::bridge::qobject
