// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
// This file was auto generated by qt_type_gen package
// from the input file://./../../../../../../../code_gen/qt_type_gen/src/input/testlib/qsignalspy.rs

#include "qsignalspy.h"

namespace rust::bridge::qsignalspy {

std::unique_ptr<QSignalSpy> inlineCppFn_new(QObject const &qobject, rust::Str signal_name)
{
    const QByteArray signalNameBa = RustStrToQByteArray(signal_name);
    const auto *mo = qobject.metaObject();
    const auto methodCount = mo->methodCount();
    for (int m = 0; m < methodCount; ++m) {
        auto method = mo->method(m);
        if (method.nameView() == signalNameBa) {
            auto sign = method.methodSignature();
            const char signalCodeChar = '0' + QSIGNAL_CODE;
            sign.insert(0, signalCodeChar);
            return std::make_unique<QSignalSpy>(&qobject, sign.constData());
        }
    }
    return nullptr;
}

ptrdiff_t inlineCppFn_count(QSignalSpy const &self)
{
    return self.count();
}

QVariantList inlineCppFn_take_at(QSignalSpy &self, ptrdiff_t idx)
{
    return self.takeAt(idx);
}

QVariantList inlineCppFn_take_first(QSignalSpy &self)
{
    return self.takeFirst();
}

QVariantList inlineCppFn_take_last(QSignalSpy &self)
{
    return self.takeLast();
}

} // namespace rust::bridge::qsignalspy
