# Copyright (C) 2026 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "qtbridge-gen"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Qt Bridge: Generative macros for QObjects"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { workspace = true, features = ["span-locations"] }
quote.workspace = true
syn.workspace = true
qtbridge-gen-common = { workspace = true }
qtbridge-build-utils = { workspace = true }

[features]
# Make #[qobject] emit automatic QML registration via the linkme crate.
linkme = []

[dev-dependencies]
insta = { version = "1", features = ["glob"] }
