# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "tst_qtbridge_gen_common"
version = "0.1.0"
edition.workspace = true
description = "Tests of qtbridge_gen_common functionality"

[dependencies]
qtbridge-gen-common = { path = "../../crates/qtbridge-gen-common" }
