// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
// This file was auto generated by qt_type_gen package
// from the input file://./../../../../../../../code_gen/qt_type_gen/src/input/core/qmetatypeinterface.rs

#include "qmetatypeinterface.h"

namespace rust::bridge::qmetatypeinterface {

using namespace QtPrivate;

::QtPrivate::QMetaTypeInterface inlineCppFn_fill_fields(uint16_t align, uint32_t size,
                                                        uint32_t flags,
                                                        rust::Slice<uint8_t const> name,
                                                        size_t meta_obj_fn, size_t default_ctr_fn,
                                                        size_t copy_ctr_fn, size_t dtor_fn)
{
    auto metaObjFn = reinterpret_cast<QMetaTypeInterface::MetaObjectFn>(meta_obj_fn);
    auto defaultCtr = reinterpret_cast<QMetaTypeInterface::DefaultCtrFn>(default_ctr_fn);
    auto copyCtr = reinterpret_cast<QMetaTypeInterface::CopyCtrFn>(copy_ctr_fn);
    auto dtor = reinterpret_cast<QMetaTypeInterface::DtorFn>(dtor_fn);
    return QMetaTypeInterface{ QMetaTypeInterface::CurrentRevision,
                               align,
                               size,
                               flags,
                               { 0 },
                               metaObjFn,
                               reinterpret_cast<const char *>(name.data()),
                               defaultCtr,
                               copyCtr,
                               nullptr,
                               dtor,
                               nullptr,
                               nullptr,
                               nullptr,
                               nullptr,
                               nullptr,
                               nullptr };
}

::QtPrivate::QMetaTypeInterface inlineCppFn_qqml_list_property_for(QMetaType const &element)
{
    const QtPrivate::QMetaTypeInterface *base =
            QMetaType::fromType<QQmlListProperty<QObject>>().iface();
    auto *name = new QByteArray(QByteArrayLiteral("QQmlListProperty<") + element.name() + '>');
    return QMetaTypeInterface{ base->revision,
                               base->alignment,
                               base->size,
                               base->flags,
                               { 0 },
                               base->metaObjectFn,
                               name->constData(),
                               base->defaultCtr,
                               base->copyCtr,
                               base->moveCtr,
                               base->dtor,
                               base->equals,
                               base->lessThan,
                               base->debugStream,
                               base->dataStreamOut,
                               base->dataStreamIn,
                               base->legacyRegisterOp };
}

} // namespace rust::bridge::qmetatypeinterface
