# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "qtbridge-build-utils"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Build utilities for qtbridge."

[dependencies]
qt-build-utils = { workspace = true }
cc = "1"
