# Copyright (C) 2025 The Qt Company Ltd.
# SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only

[package]
name = "quicktest"
version = "0.1.0"
edition.workspace = true
description = "Utilities to test interoparbility between rust and qml"

[dependencies]
cxx.workspace = true
cxx-qt-lib.workspace = true
qtbridge-type-lib = { path = "../crates/qtbridge-type-lib" }
quicktest_gen = { path = "quicktest_gen" }

[build-dependencies]
qtbridge-build-utils = { path = "../crates/qtbridge-build-utils" }
cxx-build.workspace = true
