// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
// This file was auto generated by qt_type_gen package
// from the input file://./../../../../../../../code_gen/qt_type_gen/src/input/core/qqmllistproperty.rs

#include "qqmllistproperty.h"

namespace rust::bridge::qqmllistproperty {

QVariant inlineCppFn_list_property_to_qvariant(QMetaType const &meta_type, QObject *object,
                                               uint8_t *data, size_t append_fn, size_t count_fn,
                                               size_t at_fn, size_t clear_fn)
{
    auto appendFn = reinterpret_cast<QQmlListProperty<QObject>::AppendFunction>(append_fn);
    auto countFn = reinterpret_cast<QQmlListProperty<QObject>::CountFunction>(count_fn);
    auto atFn = reinterpret_cast<QQmlListProperty<QObject>::AtFunction>(at_fn);
    auto clearFn = reinterpret_cast<QQmlListProperty<QObject>::ClearFunction>(clear_fn);
    QQmlListProperty<QObject> prop(object, static_cast<void *>(data), appendFn, countFn, atFn,
                                   clearFn);
    return QVariant(meta_type, &prop);
}

} // namespace rust::bridge::qqmllistproperty
