// Copyright (C) 2025 The Qt Company Ltd.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR LGPL-3.0-only
// This file was auto generated by qt_type_gen package
// from the input file://./../../../../../../code_gen/qt_type_gen/src/input/core/qmetatypeinterface.rs

use crate::QMetaType;
use std::mem::MaybeUninit;
#[cxx::bridge]
mod ffi {
    unsafe extern "C++" {
        include!("qtbridge-type-lib/src/core/qmetatypeinterface/cpp/qmetatypeinterface.h");
        #[allow(dead_code)]
        #[namespace = "QtPrivate"]
        type QMetaTypeInterface = super::QMetaTypeInterface;
        include!("qtbridge-type-lib/src/core/qmetatype/cpp/qmetatype.h");
        type QMetaType = crate::QMetaType;
    }
    #[namespace = "rust::bridge::qmetatypeinterface"]
    unsafe extern "C++" {
        # [rust_name = inline_cpp_fn_fill_fields]
        fn inlineCppFn_fill_fields(
            align: u16,
            size: u32,
            flags: u32,
            name: &[u8],
            meta_obj_fn: usize,
            default_ctr_fn: usize,
            copy_ctr_fn: usize,
            dtor_fn: usize,
        ) -> QMetaTypeInterface;
        # [rust_name = inline_cpp_fn_qqml_list_property_for]
        fn inlineCppFn_qqml_list_property_for(element: &QMetaType) -> QMetaTypeInterface;
    }
}
#[doc(hidden)]
/// If a QMetaType is generated based on QMetaTypeInterface it must have a
/// constant address in memory during the whole application run.
#[repr(C)]
pub struct QMetaTypeInterface {
    _revision: MaybeUninit<u16>,
    _alignment: MaybeUninit<u16>,
    _size: MaybeUninit<u32>,
    _flags: MaybeUninit<u32>,
    _type_id: MaybeUninit<i32>,
    _meta_object_fn: MaybeUninit<usize>,
    _name: MaybeUninit<usize>,
    _default_ctr: MaybeUninit<usize>,
    _copy_ctr: MaybeUninit<usize>,
    _move_ctr: MaybeUninit<usize>,
    _dtor: MaybeUninit<usize>,
    _equals: MaybeUninit<usize>,
    _less_than: MaybeUninit<usize>,
    _debug_stream: MaybeUninit<usize>,
    _data_stream_out: MaybeUninit<usize>,
    _data_stream_in: MaybeUninit<usize>,
    _legacy_register_op: MaybeUninit<usize>,
}
unsafe impl cxx::ExternType for QMetaTypeInterface {
    type Id = cxx::type_id!("QtPrivate::QMetaTypeInterface");
    type Kind = cxx::kind::Trivial;
}
impl QMetaTypeInterface {
    #[allow(dead_code)]
    pub fn fill_fields(
        align: usize,
        size: usize,
        flags: u32,
        name: &[u8],
        meta_obj_fn: usize,
        default_ctr_fn: usize,
        copy_ctr_fn: usize,
        dtor_fn: usize,
    ) -> QMetaTypeInterface {
        let cpp = ffi::inline_cpp_fn_fill_fields;
        cpp(align as u16, size as u32, flags, name, meta_obj_fn, default_ctr_fn, copy_ctr_fn, dtor_fn)
    }
    #[allow(dead_code)]
    /// The list metatype interface for an element type: a clone of `QQmlListProperty<QObject>`
    /// (layout-identical to any `QQmlListProperty<T>`), named `QQmlListProperty<{element.name}>`
    /// with the cached typeId reset to 0 so it registers as a fresh, distinct type.
    ///
    /// The name is derived from `element`'s own registered name (so the list and element types
    /// can't drift apart) and leaked in C++.
    pub fn qqml_list_property_for(element: &QMetaType) -> QMetaTypeInterface {
        ffi::inline_cpp_fn_qqml_list_property_for(element)
    }
}
